<?php
/*********************************************************************************
 * SugarCRM Community Edition is a customer relationship management program developed by
 * SugarCRM, Inc. Copyright (C) 2004-2013 SugarCRM Inc.
 * 
 * This program is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Affero General Public License version 3 as published by the
 * Free Software Foundation with the addition of the following permission added
 * to Section 15 as permitted in Section 7(a): FOR ANY PART OF THE COVERED WORK
 * IN WHICH THE COPYRIGHT IS OWNED BY SUGARCRM, SUGARCRM DISCLAIMS THE WARRANTY
 * OF NON INFRINGEMENT OF THIRD PARTY RIGHTS.
 * 
 * This program is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE.  See the GNU Affero General Public License for more
 * details.
 * 
 * You should have received a copy of the GNU Affero General Public License along with
 * this program; if not, see http://www.gnu.org/licenses or write to the Free
 * Software Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA
 * 02110-1301 USA.
 * 
 * You can contact SugarCRM, Inc. headquarters at 10050 North Wolfe Road,
 * SW2-130, Cupertino, CA 95014, USA. or at email address contact@sugarcrm.com.
 * 
 * The interactive user interfaces in modified source and object code versions
 * of this program must display Appropriate Legal Notices, as required under
 * Section 5 of the GNU Affero General Public License version 3.
 * 
 * In accordance with Section 7(b) of the GNU Affero General Public License version 3,
 * these Appropriate Legal Notices must retain the display of the "Powered by
 * SugarCRM" logo. If the display of the logo is not reasonably feasible for
 * technical reasons, the Appropriate Legal Notices must display the words
 * "Powered by SugarCRM".
 ********************************************************************************/

$relationships = array (
  'accounts_gbia3_anexo3_1' => 
  array (
    'id' => '28192097-8efa-0d1b-0cde-53f4bf9511da',
    'relationship_name' => 'accounts_gbia3_anexo3_1',
    'lhs_module' => 'Accounts',
    'lhs_table' => 'accounts',
    'lhs_key' => 'id',
    'rhs_module' => 'GBIA3_ANEXO3',
    'rhs_table' => 'gbia3_anexo3',
    'rhs_key' => 'id',
    'join_table' => 'accounts_gbia3_anexo3_1_c',
    'join_key_lhs' => 'accounts_gbia3_anexo3_1accounts_ida',
    'join_key_rhs' => 'accounts_gbia3_anexo3_1gbia3_anexo3_idb',
    'relationship_type' => 'one-to-many',
    'relationship_role_column' => NULL,
    'relationship_role_column_value' => NULL,
    'reverse' => '0',
    'deleted' => '0',
    'readonly' => true,
    'rhs_subpanel' => 'default',
    'lhs_subpanel' => NULL,
    'from_studio' => true,
    'is_custom' => true,
    'relationship_only' => false,
    'for_activities' => false,
  ),
  'gbia3_anexo3_aut_autorizacionestelefonicas_1' => 
  array (
    'id' => '2e1983f4-de3c-7622-d3ae-53f4bf250754',
    'relationship_name' => 'gbia3_anexo3_aut_autorizacionestelefonicas_1',
    'lhs_module' => 'GBIA3_ANEXO3',
    'lhs_table' => 'gbia3_anexo3',
    'lhs_key' => 'id',
    'rhs_module' => 'AUT_AutorizacionesTelefonicas',
    'rhs_table' => 'aut_autorizacionestelefonicas',
    'rhs_key' => 'id',
    'join_table' => 'gbia3_anexo3_aut_autorizacionestelefonicas_1_c',
    'join_key_lhs' => 'gbia3_anexo3_aut_autorizacionestelefonicas_1gbia3_anexo3_ida',
    'join_key_rhs' => 'gbia3_anexb7affonicas_idb',
    'relationship_type' => 'one-to-many',
    'relationship_role_column' => NULL,
    'relationship_role_column_value' => NULL,
    'reverse' => '0',
    'deleted' => '0',
    'readonly' => true,
    'rhs_subpanel' => NULL,
    'lhs_subpanel' => NULL,
    'from_studio' => true,
    'is_custom' => true,
    'relationship_only' => false,
    'for_activities' => false,
  ),
  'gbia3_anexo3_documents_1' => 
  array (
    'id' => '34f77b7f-bca2-c018-2d9e-53f4bf65f114',
    'relationship_name' => 'gbia3_anexo3_documents_1',
    'lhs_module' => 'GBIA3_ANEXO3',
    'lhs_table' => 'gbia3_anexo3',
    'lhs_key' => 'id',
    'rhs_module' => 'Documents',
    'rhs_table' => 'documents',
    'rhs_key' => 'id',
    'join_table' => 'gbia3_anexo3_documents_1_c',
    'join_key_lhs' => 'gbia3_anexo3_documents_1gbia3_anexo3_ida',
    'join_key_rhs' => 'gbia3_anexo3_documents_1documents_idb',
    'relationship_type' => 'one-to-many',
    'relationship_role_column' => NULL,
    'relationship_role_column_value' => NULL,
    'reverse' => '0',
    'deleted' => '0',
    'readonly' => true,
    'rhs_subpanel' => 'default',
    'lhs_subpanel' => NULL,
    'from_studio' => true,
    'is_custom' => true,
    'relationship_only' => false,
    'for_activities' => false,
  ),
  'gbia3_anexo3_gbia3_manejointegral_1' => 
  array (
    'id' => '41357169-0bec-7bf7-b8fa-53f4bf215758',
    'relationship_name' => 'gbia3_anexo3_gbia3_manejointegral_1',
    'lhs_module' => 'GBIA3_ANEXO3',
    'lhs_table' => 'gbia3_anexo3',
    'lhs_key' => 'id',
    'rhs_module' => 'GBIA3_ManejoIntegral',
    'rhs_table' => 'gbia3_manejointegral',
    'rhs_key' => 'id',
    'join_table' => 'gbia3_anexo3_gbia3_manejointegral_1_c',
    'join_key_lhs' => 'gbia3_anexo3_gbia3_manejointegral_1gbia3_anexo3_ida',
    'join_key_rhs' => 'gbia3_anexo3_gbia3_manejointegral_1gbia3_manejointegral_idb',
    'relationship_type' => 'one-to-many',
    'relationship_role_column' => NULL,
    'relationship_role_column_value' => NULL,
    'reverse' => '0',
    'deleted' => '0',
    'readonly' => true,
    'rhs_subpanel' => 'default',
    'lhs_subpanel' => NULL,
    'from_studio' => true,
    'is_custom' => true,
    'relationship_only' => false,
    'for_activities' => false,
  ),
  'gbia3_anexo3_gbihi_historialcorreo_1' => 
  array (
    'id' => '4d70391c-6654-b5f0-34b9-53f4bf790443',
    'relationship_name' => 'gbia3_anexo3_gbihi_historialcorreo_1',
    'lhs_module' => 'GBIA3_ANEXO3',
    'lhs_table' => 'gbia3_anexo3',
    'lhs_key' => 'id',
    'rhs_module' => 'GBIHI_HistorialCorreo',
    'rhs_table' => 'gbihi_historialcorreo',
    'rhs_key' => 'id',
    'join_table' => 'gbia3_anexo3_gbihi_historialcorreo_1_c',
    'join_key_lhs' => 'gbia3_anexo3_gbihi_historialcorreo_1gbia3_anexo3_ida',
    'join_key_rhs' => 'gbia3_anexo3_gbihi_historialcorreo_1gbihi_historialcorreo_idb',
    'relationship_type' => 'one-to-many',
    'relationship_role_column' => NULL,
    'relationship_role_column_value' => NULL,
    'reverse' => '0',
    'deleted' => '0',
    'readonly' => true,
    'rhs_subpanel' => 'default',
    'lhs_subpanel' => NULL,
    'from_studio' => true,
    'is_custom' => true,
    'relationship_only' => false,
    'for_activities' => false,
  ),
  'gbia3_anexo3_tasks_1' => 
  array (
    'id' => '559d7f71-d3c5-9960-feec-53f4bfcadf40',
    'relationship_name' => 'gbia3_anexo3_tasks_1',
    'lhs_module' => 'GBIA3_ANEXO3',
    'lhs_table' => 'gbia3_anexo3',
    'lhs_key' => 'id',
    'rhs_module' => 'Tasks',
    'rhs_table' => 'tasks',
    'rhs_key' => 'id',
    'join_table' => 'gbia3_anexo3_tasks_1_c',
    'join_key_lhs' => 'gbia3_anexo3_tasks_1gbia3_anexo3_ida',
    'join_key_rhs' => 'gbia3_anexo3_tasks_1tasks_idb',
    'relationship_type' => 'one-to-many',
    'relationship_role_column' => NULL,
    'relationship_role_column_value' => NULL,
    'reverse' => '0',
    'deleted' => '0',
    'readonly' => true,
    'rhs_subpanel' => 'default',
    'lhs_subpanel' => NULL,
    'from_studio' => true,
    'is_custom' => true,
    'relationship_only' => false,
    'for_activities' => false,
  ),
  'gbia4_anexo4_gbia3_anexo3' => 
  array (
    'id' => '5dc3a050-77ca-a5a7-5079-53f4bf034eb2',
    'relationship_name' => 'gbia4_anexo4_gbia3_anexo3',
    'lhs_module' => 'GBIA3_ANEXO3',
    'lhs_table' => 'gbia3_anexo3',
    'lhs_key' => 'id',
    'rhs_module' => 'gbiA4_Anexo4',
    'rhs_table' => 'gbia4_anexo4',
    'rhs_key' => 'id',
    'join_table' => 'gbia4_anexo4_gbia3_anexo3_c',
    'join_key_lhs' => 'gbia4_anexo4_gbia3_anexo3gbia3_anexo3_ida',
    'join_key_rhs' => 'gbia4_anexo4_gbia3_anexo3gbia4_anexo4_idb',
    'relationship_type' => 'one-to-many',
    'relationship_role_column' => NULL,
    'relationship_role_column_value' => NULL,
    'reverse' => '0',
    'deleted' => '0',
    'readonly' => true,
    'rhs_subpanel' => 'default',
    'lhs_subpanel' => NULL,
    'is_custom' => true,
    'relationship_only' => false,
    'for_activities' => false,
    'from_studio' => true,
  ),
  'gbia3_anexo3_modified_user' => 
  array (
    'id' => '6279c2a8-1791-ffb4-0323-53f4bf5c23d9',
    'relationship_name' => 'gbia3_anexo3_modified_user',
    'lhs_module' => 'Users',
    'lhs_table' => 'users',
    'lhs_key' => 'id',
    'rhs_module' => 'GBIA3_ANEXO3',
    'rhs_table' => 'gbia3_anexo3',
    'rhs_key' => 'modified_user_id',
    'join_table' => NULL,
    'join_key_lhs' => NULL,
    'join_key_rhs' => NULL,
    'relationship_type' => 'one-to-many',
    'relationship_role_column' => NULL,
    'relationship_role_column_value' => NULL,
    'reverse' => '0',
    'deleted' => '0',
    'readonly' => true,
    'rhs_subpanel' => NULL,
    'lhs_subpanel' => NULL,
    'relationship_only' => false,
    'for_activities' => false,
    'is_custom' => false,
    'from_studio' => true,
  ),
  'gbia3_anexo3_created_by' => 
  array (
    'id' => '655b750f-1769-5f87-89e0-53f4bf74f873',
    'relationship_name' => 'gbia3_anexo3_created_by',
    'lhs_module' => 'Users',
    'lhs_table' => 'users',
    'lhs_key' => 'id',
    'rhs_module' => 'GBIA3_ANEXO3',
    'rhs_table' => 'gbia3_anexo3',
    'rhs_key' => 'created_by',
    'join_table' => NULL,
    'join_key_lhs' => NULL,
    'join_key_rhs' => NULL,
    'relationship_type' => 'one-to-many',
    'relationship_role_column' => NULL,
    'relationship_role_column_value' => NULL,
    'reverse' => '0',
    'deleted' => '0',
    'readonly' => true,
    'rhs_subpanel' => NULL,
    'lhs_subpanel' => NULL,
    'relationship_only' => false,
    'for_activities' => false,
    'is_custom' => false,
    'from_studio' => true,
  ),
  'gbia3_anexo3_assigned_user' => 
  array (
    'id' => '696f261b-fe7e-dcf0-9d39-53f4bfc4d170',
    'relationship_name' => 'gbia3_anexo3_assigned_user',
    'lhs_module' => 'Users',
    'lhs_table' => 'users',
    'lhs_key' => 'id',
    'rhs_module' => 'GBIA3_ANEXO3',
    'rhs_table' => 'gbia3_anexo3',
    'rhs_key' => 'assigned_user_id',
    'join_table' => NULL,
    'join_key_lhs' => NULL,
    'join_key_rhs' => NULL,
    'relationship_type' => 'one-to-many',
    'relationship_role_column' => NULL,
    'relationship_role_column_value' => NULL,
    'reverse' => '0',
    'deleted' => '0',
    'readonly' => true,
    'rhs_subpanel' => NULL,
    'lhs_subpanel' => NULL,
    'relationship_only' => false,
    'for_activities' => false,
    'is_custom' => false,
    'from_studio' => true,
  ),
  'gbia3_anexo3_calls_1' => 
  array (
    'rhs_label' => 'Llamadas',
    'lhs_label' => 'ANEXO 3',
    'rhs_subpanel' => 'default',
    'lhs_module' => 'GBIA3_ANEXO3',
    'rhs_module' => 'Calls',
    'relationship_type' => 'one-to-many',
    'readonly' => true,
    'deleted' => false,
    'relationship_only' => false,
    'for_activities' => false,
    'is_custom' => false,
    'from_studio' => true,
    'relationship_name' => 'gbia3_anexo3_calls_1',
  ),
);